version: '2'
services:
    microservice-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/microservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=microservice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
