apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-gateway-ui
  labels:
    app: api-gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /api/
          backend:
              serviceName: api-gateway
              servicePort: web
        - path: /uaa/
          backend:
              serviceName: api-gateway
              servicePort: web
        - path: /auth/
          backend:
              serviceName: api-gateway
              servicePort: web
        - path: /microservice/
          backend:
              serviceName: api-gateway
              servicePort: web
        - path: /
          backend:
              serviceName: example-ui
              servicePort: 80

