version: '2'
services:
    microservice-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/microservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=microservice
            - POSTGRES_PASSWORD=
        container_name: microservice-db
        ports:
            - 5432:5432
