apiVersion: v1
data:
  # This site has a nice breakdown of the different options for logrotate https://linux.die.net/man/8/logrotate
  nginx: |
    /var/log/nginx/*log {
        daily
    }

kind: ConfigMap
metadata:
  name: ui-nginx-log-rotate-conf
  labels:
    app: example-ui
    component: user-interface
