apiVersion: v1
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        log_format main 'time_local="$time_local" status="$status" '
                 'uri_query="$query_string" uri_path="$uri" '
                 'http_method="$request_method" ';

        error_log /var/log/nginx/error.log warn;
        access_log  /var/log/nginx/access.log main;
        proxy_intercept_errors off;
        proxy_send_timeout 120;
        proxy_read_timeout 300;

        types {
            text/html               html;
            text/javascript         js;
            text/css                css;
            image/png               png;
            image/jpg               jpg;
            image/svg+xml           svg svgz;
            application/octet-steam eot;
            application/octet-steam ttf;
            application/octet-steam woff;
        }

        default_type    application/octet-stream;
        root /example/www/;

        server {
            listen 8080;

            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                try_files $uri $uri/ =404;
            }
        }
    }
kind: ConfigMap
metadata:
  name: ui-nginx-conf
  labels:
    app: example-ui
    component: user-interface
