apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-db
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: microservice
        component: database
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.3-alpine
        env:
        - name: POSTGRES_USER
          value: microservice
        - name: POSTGRES_PASSWORD
          value:
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 150m
            memory: 0.15Gi
          limits:
            cpu: 165m
            memory: 0.165Gi
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: microservice-pg-pv-claim
